### ISSUE TITLE
Error in sample code - missing parens after search methods

### ISSUE THREAD

**Issue by davidreedernst** [danieldevine/bird-docs#4]
I was excited to find BirdElephant, looks like a great tool for a project I'm working on. However, as I was just getting my feet wet, I got frustrated just trying to run the sample code on https://birdelephant.com/tweets. Specifically, this line:

`$tweets->search->recent($params);`

was resulting in the errors: 

`PHP Notice:  Undefined property: Coderjerk\BirdElephant\Tweets::$search`
`PHP Fatal error:  Uncaught Error: Call to a member function recent() on null`

Perhaps to most people the problem is immediately obvious, but it took me some hair-pulling and code-searching to realize that the sample code really should have been 

`$tweets->search()->recent($params);`

That is, there should be a pair of parens after "search".  It looks like several other bits of sample code on that page have the same issue, for instance 

`$tweets->count->recent($params);`

(I didn't do a thorough search for other examples of the problem. There are likely several others.)

Unrelated issue: I think it would be helpful if the sample code in the docs gave examples of how to actually use the results of the method calls.  So maybe something like: 

`echo $tweets->count()->recent($params)->meta->total_tweet_count;`

and going back to search, something like

`foreach ($tweets->search()->recent($params)->data as $t) {
    echo $t->text . "\n";
}`

Obviously, I was able to figure this stuff out using var_dumps and the like, but having it more apparent in the sample code would definitely be helpful.

Thanks again for your work on this! Now that I'm over these hurdles, I'm excited to start using BirdElephant in my work!

**Comment by danieldevine** [comment]
Thanks for flagging, I'm sure the docs are absolutely full of typos. I haven't much bandwidth at the moment to fix this so a pull request would be appreciated. 

On the other topic you raised, I am planning to do a couple of tutorials on common uses when (if) I eventually get some spare time. That said though, the library is intentionally agnostic about what users do with it beyond retrieving/sending data so I won't be heading too far down that path in the main docs.
